version: 2

builds:
  - id: kaimz_backend
    main: ./cmd/main.go
    binary: kaimz_backend
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - id: kaimz_backend_archive
    builds:
      - kaimz_backend
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: false
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
